---
- hosts: 172.31.33.245
  become: yes
  tasks:
  - name: i want to install webserver 
    yum:
     name: httpd
     state: present
  - name: i wnant copy my index file into ansible node
    template:
     src: index.j2
     dest: /var/www/html/index.html   