---
- hosts: 172.31.39.146
  become: yes
  tasks:
  - name: i want execute linux commands directly
    command: hostname -f
    register: myresult

  - name: i wnat to display my first task result
    debug:
     msg: "{{myresult}}"  