---
- hosts: 172.31.39.146
  become: yes
  vars:
   myvar1: git
   myvar2: tree
   myvar3: wget
  tasks:
  - name: install git
    apt:
     name: "{{myvar1}}" 
     state: present
  - name: i wnat to display myvar1
    debug:
     msg: "{{myvar1}}"   