---
- hosts: all
  become: yes
  tasks:
  - name: i want to install git on ansible ubuntu node
    apt:
     name: git
     state: present
    when: ansible_os_family=="Debian"   

  - name: i want start webserver on ubuntu node
    service: 
      name: "{{mywebpackforubuntu}}"
      state: started    
    when: ansible_os_family=="Debian"


  - name: i want install webserver on ansible rehat node
    yum:
     name: "{{mywebpackforredhat}}"
     state: present
    when: ansible_os_family=="RedHat"


  - name: i want install webserver on ansible redhat node
    service:
     name: "{{mywebpackforredhat}}"
     state: started
    when: ansible_os_family=="RedHat" 