---
- hosts: all
  become: yes
  tasks:
  - name: i want to install git on ansible ubuntu node
    apt:
     name: git
     state: present
    when: ansible_os_family=="Debian"   

  - name: i want start webserver on ubuntu node
    service: 
      name: apache2
      state: started    
    when: ansible_os_family=="Debian"  